# Generated by Django 3.1.2 on 2020-10-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cities',
            name='lng',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
